services:
  mysql:
    image: mysql:8.0
    container_name: lighthouse-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: lighthouse_root_password
      MYSQL_DATABASE: lighthouse
      MYSQL_USER: lighthouse_user
      MYSQL_PASSWORD: lighthouse_password
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.db:/docker-entrypoint-initdb.d
    networks:
      - lighthouse-network
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: lighthouse-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    networks:
      - lighthouse-network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 5

  localstack:
    image: localstack/localstack:latest
    container_name: lighthouse-localstack
    restart: unless-stopped
    ports:
      - '4566:4566' # LocalStack Gateway
      - '4571:4571' # External services
    environment:
      - SERVICES=s3,sqs,sns,dynamodb
      - DEBUG=0
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - ./scripts/init-localstack.sh:/docker-entrypoint-initaws.d/init-localstack.sh
    networks:
      - lighthouse-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:4566/_localstack/health']
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  lighthouse-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
